[project]
name = "cdse-dl"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Tyler", email = "31015976+tylanderson@users.noreply.github.com" },
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
lint.select = ["E4", "E7", "E9", "F", "I", "D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
